name: Publish Package to npmjs

on:
  push:
    branches: [ main ]
    
jobs:
  install_ved:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies ğŸ“¦ï¸
      - run: npm install
  build_ved:
    runs-on: ubuntu-latest
    steps:
      - name: Build project ğŸ”§
        run: |
          npm run build
  pubish_ved:
    runs-on: ubuntu-latest
    steps:
      -name: Publish to npmjs ğŸš€
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}